export { default as Lecturer } from './Lecturer/Lecturer';
export { default as Home } from './Home/Home';
export { default as Layout } from './Layout/Layout';
export { default as Student } from './Student/Student';
export { default as ShowStudent } from './Student/Show/ShowStudent';
export { default as Class } from './Class/Class';
export { default as City } from './City/City';
export { default as Course } from './Course/Course';
export { default as Score } from './Score/Score';
export { default as Ipk } from './Ipk/Ipk';
export { default as Footer } from './Layout/Footer';
export { default as Login } from './Auth/Login';
export { default as Register } from './Auth/Register';
export { default as ShowClass } from './Course/Attendance/ShowClass'